export const desktopIconArray = [
    { name: 'gabber', position: 1, empty: false },
    { name: 'bio', position: 2, empty: true },
    { name: 'videos', position: 3, empty: false },
    { name: 'null', position: 4, empty: true },
    { name: 'null', position: 5, empty: true },
    { name: 'pics', position: 6, empty: true },
    { name: 'null', position: 7, empty: true },
    { name: 'micro-machines', position: 8, empty: false },
    { name: 'Icon9', position: 9, empty: true },
    { name: 'Icon10', position: 10, empty: true },
    { name: 'Icon11', position: 11, empty: true },
    { name: 'Icon12', position: 12, empty: true },
    { name: 'Icon13', position: 13, empty: true },
    { name: 'Icon14', position: 14, empty: true },
    { name: 'party-time', position: 15, empty: false },
    { name: 'Icon16', position: 16, empty: true },
    { name: 'Icon17', position: 17, empty: true },
    { name: 'Icon18', position: 18, empty: true },
    { name: 'Icon19', position: 19, empty: true },
    { name: 'Icon20', position: 20, empty: true },
    { name: 'Icon21', position: 21, empty: true },
    { name: 'smoking-section', position: 22, empty: false },
    { name: 'Icon23', position: 23, empty: true },
    { name: 'Icon24', position: 24, empty: true },
    { name: 'Icon25', position: 25, empty: true },
    { name: 'Icon26', position: 26, empty: true },
    { name: 'Icon27', position: 27, empty: true },
    { name: 'recycle', position: 28, empty: false },
];

export const mobileIconArray = [
    { name: 'gabber', position: 1, empty: false },
    { name: 'null', position: 2, empty: true },
    { name: 'null', position: 3, empty: true },
    { name: 'null', position: 4, empty: true },
    { name: 'null', position: 5, empty: true },
    { name: 'null', position: 6, empty: true },
    { name: 'bio', position: 7, empty: true },
    { name: 'null', position: 8, empty: true },
    { name: 'videos', position: 9, empty: false },
    { name: 'micro-machines', position: 10, empty: false },
    { name: 'Icon11', position: 11, empty: true },
    { name: 'pics', position: 12, empty: true },
    { name: 'party-time', position: 13, empty: false },
    { name: 'smoking-section', position: 14, empty: true },
    { name: 'recycle', position: 15, empty: false },
];
